services:
  mysql:
    image: mysql:8.4
    container_name: finance-mysql
    environment:
      MYSQL_DATABASE: finance_db
      MYSQL_USER: finance_user
      MYSQL_PASSWORD: finance_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - finance_mysql_data:/var/lib/mysql

volumes:
  finance_mysql_data: